site_name: CERULEo
theme:
  name: "material"
  features:
    - navigation.tabs

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: true
          show_root_heading: false
          heading_level: 3
          show_root_toc_entry: false
          group_by_category: true
- autorefs
- mkdocs-jupyter
- bibtex:
    bib_file: "docs/refs.bib"

watch:
  - ceruleo


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      toc_depth: 3
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta