site_name: CeRULEo
theme:
  name: "material"
  palette:
    primary: light blue
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow


nav:
    - CeRULEo: ../
    - Dataset:
      - Dataset: dataset/dataset.md
      - Catalog: dataset/catalog.md
      - Visualization: dataset/visualization.md
      - Example: dataset/Example.ipynb
      - Analysis:
        - Sensor validation: dataset/analysis/sensor_validation.md
        - Correlation: dataset/analysis/correlation.md
        - Distribution: dataset/analysis/distribution.md
        - Sample Rate: dataset/analysis/sample_rate.md
        - Example: dataset/analysis/Sensor Validation.ipynb
    - Iterators: 
      - Iterators: iterators/iterators.md
      - Shufflers: iterators/shufflers.md
      - Batcher: iterators/batcher.md
      - Example: iterators/Iterators.ipynb
    - Models: 
      - Baselines: models/baseline.md
      - Scikit-learn: models/sklearn.md
      - Tensorflow:
        - Iterators: models/keras/index.md
        - Catalog: models/keras/catalog/models.md
      - Examples:
        - Example: models/Models.ipynb
        - Scikit-learn:  models/Models_sklearn.ipynb
        - Tensorflow: models/models_tf.ipynb
    - Transformation:       
      - Trasformers: transformation/transformers.md
      - Pipeline: transformation/pipeline.md
      - Features:
        - Cast: transformation/features/cast.md
        - Denoising: transformation/features/denoising.md
        - Entropy: transformation/features/entropy.md
        - Extraction: transformation/features/extraction.md
        - Imputers: transformation/features/imputers.md
        - Resamplers: transformation/features/resamplers.md
        - Resamplers: transformation/features/selection.md
        - Outliers: transformation/features/outliers.md
    - Results:
      - Results: results/results.md
      - Visualization: results/visualization.md
    - Guides:
      - Complete: guides/guide.ipynb
      
    


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: true
          show_root_heading: false
          heading_level: 3
          show_root_toc_entry: false
          group_by_category: true
- autorefs
- mkdocs-jupyter
- bibtex:
    bib_file: "docs/refs.bib"

watch:
  - ceruleo


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      toc_depth: 5
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta