

name: Documentation


on:
  push:
    branches: [ main ]


jobs:
  
  doc:
    runs-on: ubuntu-latest
   
    steps:

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install -y pandoc                 
          python -m pip install --upgrade pip          
          python -m pip install flake8 pytest coverage
          python -m pip install wheel setuptools cython
          python -m pip install tensorflow
          python -m pip install --upgrade nbconvert
          python -m pip install  jinja2
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install -e $GITHUB_WORKSPACE


      - name: Deploy docs
        run: |
          mkdocs gh-deploy --force
        
